[package]
name = "mecis-rocket"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.3.10"
default-features = false
features = ["handlebars_templates"]

[dependencies.rusqlite]
version = "0.11.0"
features = ["bundled"]

